version: '3.7'

services:
  backend:
    container_name: backend
    image: expense-tracker-backend:latest
    build: .
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    restart: on-failure
    env_file:
      - .env

  database:
    container_name: database
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 10s
